#!/bin/bash -ex

pushd `dirname $0` > /dev/null
SCRIPTPATH=`pwd -P`
popd > /dev/null

echo Setting up Python virtual environment
BUILDDIR=$(pwd)/build
mkdir -p "${BUILDDIR}"

python3 -m venv build/venv
. build/venv/bin/activate

echo Adding pyinstaller
# aarch64 requires a very new Pyinstaller, but our old centos6
# agent breaks with anything newer than 4.2
if [ `uname -m` == "arm64" ]; then
    PYINSTALLER_VERSION=4.5.1
else
    PYINSTALLER_VERSION=4.2
fi
pip3 install pyinstaller==${PYINSTALLER_VERSION}

echo Installing cbdep requirements
pip3 install -r ${SCRIPTPATH}/requirements.txt

# Customize _buildversion.py if build info available in environment
if [ ! -z "${VERSION}" -a ! -z "${BLD_NUM}" ]; then
    VERSIONPATH="${BUILDDIR}/version"
    mkdir -p "${VERSIONPATH}"
    cat <<EOF > "${VERSIONPATH}/_buildversion.py"
__version__ = "${VERSION}"
__build__ = "${BLD_NUM}"
EOF
else
    VERSIONPATH=""
fi

echo Compiling cb-non-package-installer
PYINSTDIR=$(pwd)/build/pyinstaller
mkdir -p ${PYINSTDIR}
pyinstaller --log-level DEBUG \
    --workpath ${PYINSTDIR} \
    --specpath ${PYINSTDIR} \
    --distpath dist --noconfirm \
    --onefile \
    --paths "${VERSIONPATH}" \
    ${SCRIPTPATH}/cb-non-package-installer
